# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.3
_src_path: https://github.com/jupyterlab/extension-template
advanced: false
author_email: konrad.jelen+github@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_kimi_code_extension
project_short_description: Jupyterlab extension for Kimi Code offering session management,
    resume and navigation similar to the other extension - jupyterlab_kimi_code_extension
python_name: jupyterlab_kimi_code_extension
repository: ''
test: true

